### PR TITLE
[PRD-5383] - Sub-Report: Inherited Data Sets don't have any fields from ...

### PR DESCRIPTION
**Pull request by akhayrutdinov**
...SQL query.

@tmorgner, @mkambol, @mdamour1976 review it please

### CODE REVIEW

**Comment by tmorgner** [comment]
What is the reason that setting an empty "CompoundDataFactory" here fixes the problem? Was there a specific exception that was generated? 

As the code is now, this fix will not fix all occurences, as Crosstabs, Table-Of-Contents and Index-Elements are also subreports and would require the same fix. In addition to these, subreports can also be inserted via the "Insert" menu and right-click) context-menu, which does not pass through this code here. So you would have to address them too.

If the existence of the data-factory is mandatory, then please move that to the "SubReport" constructor in the reporting engine instead.

**Comment by akhayrutdinov** [comment]
@tmorgner thanks for reviewing!
My approach is based on your recommendation (http://jira.pentaho.com/browse/PRD-5383?focusedCommentId=211011&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-211011). Frankly speaking, I didn't know about Crosstabs and others, so they indeed need to be handled in a proper way. But I checked copy-pasting actions and they kept working well.

My first attempt was to set null to dataFactory field, but this caused exceptions, thus I just looked at the instance while debugging and found there a CompoundFactory. So, I replaced it with an empty one.

OK, I'm going to continue working on the ticket. I'll tag you as soon as I'll carry out implementation

**Comment by akhayrutdinov** [comment]
@tmorgner, review it please.

Now, it handles both Crosstabs and plain subreports. TOC and Index are not affected since they don't show the dialog for selecting datasource from master report.

As I've mentioned, I couldn't manage to set null as a DataFactory, because it caused an error in a UI renderer:
```
java.lang.IllegalArgumentException: Last path component must be non-null
	at javax.swing.tree.TreePath.<init>(TreePath.java:105)
	at org.pentaho.reporting.designer.core.editor.structuretree.AbstractReportDataTreeModel.getPathForNode(AbstractReportDataTreeModel.java:555)
	at org.pentaho.reporting.designer.core.editor.structuretree.AbstractReportDataTreeModel.fireTreeStructureChanged(AbstractReportDataTreeModel.java:401)
	at org.pentaho.reporting.designer.core.editor.structuretree.DataReportTree$ReportUpdateHandler.handleNodeRemoved(DataReportTree.java:177)
	at org.pentaho.reporting.designer.core.editor.structuretree.DataReportTree$ReportUpdateHandler.nodeChanged(DataReportTree.java:91)
	at org.pentaho.reporting.engine.classic.core.AbstractReportDefinition.fireModelLayoutChanged(AbstractReportDefinition.java:1220)
	at org.pentaho.reporting.engine.classic.core.SubReport.updateChangedFlagInternal(SubReport.java:382)
	at org.pentaho.reporting.engine.classic.core.Element.notifyNodeChildRemoved(Element.java:999)
	at org.pentaho.reporting.engine.classic.core.SubReport.setDataFactory(SubReport.java:361)
	at org.pentaho.reporting.designer.core.editor.report.elements.AbstractSubreportHandler.showDataSourceDialog(AbstractSubreportHandler.java:112)
	at org.pentaho.reporting.designer.core.editor.report.elements.AbstractSubreportHandler.run(AbstractSubreportHandler.java:87)
	at org.pentaho.reporting.designer.core.editor.report.elements.CrosstabConfigureHandler.run(CrosstabConfigureHandler.java:40)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```
And since there is no EmptyDataFactory, I selected an empty CompoundDataFactory.

When it comes to copy-pasting via context menu I would say it works fine. If the user copies a subreport to another master report, the structure is kept, but inherited queries disappear. And I suppose it is correct, isn't it? As the query was inherited, the subreport doesn't contain it and that's why it cannot keep it during the migration.

**Comment by akhayrutdinov** [comment]
@tmorgner, review it please

**Comment by akhayrutdinov** [comment]
@tmorgner, review it please

**Comment by tmorgner** [comment]
Looks good.

**Pull request merged**
