### PR TITLE
[PRD-5884] - Creating a new JDBC data set, using the menu Bar, the da…

### PR DESCRIPTION
**Pull request by ricardosilva88**
…tasource created doesn't appears in Data section

@pentaho/millenniumfalcon 
@tmorgner

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 1m 52s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl designer/report-designer
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by ricardosilva88** [comment]
There aren't any tests for this code

**Comment by buildguy** [comment]
### :x: Build failed in 1m 15s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl designer/report-designer
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 6m 44s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl designer/report-designer
```
---
:ok_hand: All tests passed!
 
Tests run: **160**, Failures: **0**, Skipped: **14** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/reporting/job/PR-1321/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 6m 57s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl designer/report-designer
```
---
:ok_hand: All tests passed!
 
Tests run: **160**, Failures: **0**, Skipped: **14** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/reporting/job/PR-1321/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
