### PR TITLE
[SP-1614] backport of PRD-5286 - Wrong report title after publishing from PRD 

### PR DESCRIPTION
**Pull request by andrey-markelov**
Picked from https://github.com/pentaho/pentaho-reporting/pull/556/ and https://github.com/pentaho/pentaho-reporting/commit/45b2452f9fc527d6cd049d055c70f3e684f4952e 
@tmorgner

### CODE REVIEW

**Comment by tmorgner** [comment]
@andrey-markelov These changes only exist in 5.2 branch, not in master. There should be a corresponding pull request for master for these fixes. 

Note that your last pull request for master containing the refactoring was untested and thus David had to roll back the merge.

**Comment by tmorgner** [comment]
This pull request does not compile. Please, do actually test what you submit before you submit it. 

On the command line, on the root of the checked out reporting project, run 

"ant continuous-local-junit" 

and file a pull request only after this command passes correctly.

**Comment by andrey-markelov** [comment]
Hi Tomas. Modifications exist in master. Please take a look https://github.com/andrey-markelov/pentaho-reporting/blob/master/designer/report-designer/src/org/pentaho/reporting/designer/core/actions/report/SaveReportAction.java

I did not get any errors from compiler. Could you quote me it?

**Comment by tmorgner** [comment]
For some reasons, your branch SP-1642 shows and checks out files from the master branch. This tripped up the pullrequest-builder plugin which in return gave the compile errors. Manually merging against the 5.2 branch resolved that and the project indeed compiles correctly. Could it be that your base branch into which you cerry picked these commits is very old?

@rmansoor @mdamour1976 ready to merge.

**Comment by andrey-markelov** [comment]
@tmorgner  seems you're right,I had committed to a wrong branch. Please take a look:

**Pull request closed without merging**
