### PR TITLE
[PDI-19639]:"Formula" - DAYS ：The output will not be negative if the most recent date is used as the first attribute

### PR DESCRIPTION
**Pull request by PawanPonugupati**

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 27m 26s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl libraries/libformula
```
---
:ok_hand: All tests passed!
 
Tests run: **2511**, Failures: **0**, Skipped: **15** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/reporting/job/PR-1581/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by peterrinehart — CHANGES_REQUESTED** [review]
Code change looks fine, but is there a unit test verifying that this method is behaving correctly?  In the case where we're correcting a behavior, we should usually add/modify a unit test to ensure that the new behavior is working correctly.

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 35m 31s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
:ok_hand: All tests passed!
 
Tests run: **2647**, Failures: **0**, Skipped: **15** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/reporting/job/PR-1581/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 38m 5s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
:ok_hand: All tests passed!
 
Tests run: **2647**, Failures: **0**, Skipped: **15** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/reporting/job/PR-1581/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request closed without merging**
