### PR TITLE
[BACKLOG-9531] - Add email output to the publish dialog

### PR DESCRIPTION
**Pull request by EgorZhuk**
Allow user to select Email output from the publish dialog

### CODE REVIEW

**Comment by EgorZhuk** [comment]
@tmorgner  please review

**Comment by EgorZhuk** [comment]
@pamval @pentaho/orlandocalisbon please review

**Comment by EgorZhuk** [comment]
@tmorgner could you please take a look?

**Comment by tmorgner** [comment]
This is only half the fix. To make the email output appear in the "preferred-output-type" attribute, you will need to add it as extra entry to the org.pentaho.reporting.engine.classic.core.metadata.propertyeditors.ReportProcessTaskPropertyEditor as well. A "validValues.add("mime/text/html");" or so in the constructor will make it show up there as well.

**Comment by EgorZhuk** [comment]
@tmorgner The second part is merged in #800

**Pull request merged**
