### PR TITLE
[PRD-3954] DRILLDOWN Formula Editor, the Location resets unexpectedly

### PR DESCRIPTION
**Pull request by Advent51**
- removed unnecessary parameters filtration;
- added a check before event creation;
- fixed formula creation - created formula now is valid by default;
- fixed unreported bug with '=' duplication on location changing;

### CODE REVIEW

**Comment by Advent51** [comment]
@pamval @mbatchelor @stepanovdg please review

**Comment by kolinus** [comment]
@tmorgner could you please take a look

**Comment by Advent51** [comment]
@pamval @stepanovdg @tmorgner please review

**Comment by tmorgner** [comment]
This just removes some 4.8 area legacy code and thus prevents the bug. Anything that makes the code simpler is good.

**Pull request merged**
