### PR TITLE
[BACKLOG-19148]-java.lang.UnsupportedOperationException error in Pentaho Report Designer when publishing report to the server

### PR DESCRIPTION
**Pull request by stepanovdg**
Removed org.apache.karaf.jaas.modules-x.x.x.jar http://jira.pentaho.com/browse/BACKLOG-18473 
Contained old version of http-client inside.

### CODE REVIEW

**Comment by stepanovdg** [comment]
@tmorgner Could you please take a look?

**Comment by stepanovdg** [comment]
@tmorgner @duarteteixeira @pamval @mchen-len-son @kolinus Could you please take a look?

**Comment by stepanovdg** [comment]
@tmorgner @duarteteixeira @pamval @mchen-len-son @kolinus Could you please take a look?

**Comment by tmorgner** [comment]
You are handling circular redirects in the VFS handler. If I remember that right, stuff like that was/is caused by the Spring Security intercept that checks authentication credentials (if no cookie is set). That would indicate that both CDA and the report-designer module need the same config. These targets also hit the same Pentaho server with the very same Spring security playing silly games.

**Comment by stepanovdg** [comment]
@tmorgner  I just update the way params are set into client request. 
So if previously was asked for circular redirects it proceed doing that. 
We have a regression related to httpclient update. Currently should use the new way of setting params.

**Comment by stepanovdg** [comment]
@tmorgner @duarteteixeira @pamval @mchen-len-son @kolinus Could you please take a look?

**Comment by tmorgner** [comment]
Well, it seems to do same stuff as before, so it should at least not be worse than before.

**Pull request merged**
