### PR TITLE
[BACKLOG-8501] - PIR: Sometimes message "The row limit has been reach…

### PR DESCRIPTION
**Pull request by dzmitry-hryhoryeu**
[BACKLOG-8501] - PIR: Sometimes message "The row limit has been reached" disappears when row limit is applied

@tmorgner
please review

### CODE REVIEW

**Comment by tmorgner** [comment]
Shouldn't there be tests to verify your change? You apparently work on a border case, so the junit tests should exist that validate that case. If there are existing unit tests and they did not fail until now, then those tests dont cover this particular case.

**Comment by dzmitry-hryhoryeu** [comment]
Previous tests dont cover the situation when data source enforce limit itself.

**Comment by tmorgner** [comment]
There are quite a few unused imports in the test file. Can you tell your IDE to clean it up please? 
After that we'll ignore wingman for a while and merge it. Poor chap has an identity crisis and it will be a while before he's back assisting our build validation.

**Comment by dzmitry-hryhoryeu** [comment]
Unused imports was removed.

**Comment by tmorgner** [comment]
Wingman, I love you, but you really need a therapy session.

**Pull request merged**
