### PR TITLE
[SP-4785] - Backport of PPP-4167 - Assembly “pre-classic-sdk" seems t…

### PR DESCRIPTION
**Pull request by ricardosilva88**
…o be missing since 7.0 (7.1 Suite)

Back port of:
https://github.com/pentaho/pentaho-reporting/commit/c1417e8ac8fdec96f7f8965e30b34b07cdab3fe5
https://github.com/pentaho/pentaho-reporting/commit/6280083e7663b31d32ceed4aa1807eea9c363951

@pentaho-lmartins @bantonio82

### CODE REVIEW

**Comment by pentaho-lmartins** [comment]
@cardosov can you take a look at this?

**Comment by cardosov** [comment]
While comparing the artifact generated for the 7.1 with the one from 7.0, found some differences. @ricardosilva88 is looking into them.

**Comment by pentaho-lmartins** [comment]
Closing this PR since we can't have open PRs for CM Audit.

**Comment by ricardosilva88** [comment]
PR updated with remaining corrections (https://github.com/pentaho/pentaho-reporting/pull/1213/files) , that were already discussed with @cardosov during last month attempt to back port this issue.

@ppatricio @RPAraujo

**Pull request merged**
