### PR TITLE
[PPP-4660] - Use of Vulnerable Component: Components/jackson-databind:2.9.10.2

### PR DESCRIPTION
**Pull request by andreramos89**
@smmribeiro 
@bcostahitachivantara 
@renato-s

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 48s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Review by smmribeiro — APPROVED** [review]
Looks good.

**Comment by buildguy** [comment]
### :x: Build failed in 1h 27m 26s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by smmribeiro** [comment]
Closing this and all "January 2023" related PRs for this issue (check this [comment](https://hv-eng.atlassian.net/browse/PPP-4660?focusedCommentId=1546417) and this [comment](https://hv-eng.atlassian.net/browse/PPP-4660?focusedCommentId=1543281)).

Too much time has passed and the risk of a PR being incomplete (or simply wrong) is too high.
I won't delete the original branch so that anyone picking up the development can see what was done previously.

**Pull request closed without merging**
