### PR TITLE
[PRD-5754] - Json Input fields not visible with PDI datasource

### PR DESCRIPTION
**Pull request by stanislau-strelchanka**

### CODE REVIEW

**Comment by stanislau-strelchanka** [comment]
@wingman-pentaho can you please assist with errors

**Comment by stanislau-strelchanka** [comment]
@mkambol, @mdamour1976, @tmorgner, @mchen-len-son, @pamval please review

**Comment by stanislau-strelchanka** [comment]
@mkambol, @mdamour1976, @tmorgner, @mchen-len-son, @pamval, @wingman-pentaho 
'compile' target is used from 'build.assembly.sequential.xml' and it didn't depend on 'init' which
is responsible for creating devlib and other folders

please review

**Comment by stanislau-strelchanka** [comment]
moved wingman fix to #840

**Comment by stanislau-strelchanka** [comment]
@mkambol, @mdamour1976, @tmorgner, @mchen-len-son, @pamval
resolved conflicts, please review

**Comment by lucboudreau** [comment]
Wingman build coming up.

**Comment by stanislau-strelchanka** [comment]
@mkambol, @mdamour1976, @tmorgner, @mchen-len-son, @pamval, @mbatchelor please review

**Comment by tmorgner** [comment]
Wingman said: You are good to go.

**Pull request merged**
