### PR TITLE
[SP-3800] Backport of PRD-5916 - To see the default date in the repor…

### PR DESCRIPTION
**Pull request by stanislau-strelchanka**
[SP-3800] Backport of PRD-5916 - To see the default date in the report it was necessary to open the parameter dialog two times (click OK) (7.1 Suite)

### CODE REVIEW

**Comment by stanislau-strelchanka** [comment]
backport of #1017

**Comment by stanislau-strelchanka** [comment]
@tmorgner @pamval @mchen-len-son please review

**Comment by stepanovdg** [comment]
@stanislau-strelchanka Unit tests failed on local build

**Comment by tmorgner** [comment]
Yeah, there is something going on with Mondrian right now. Your changes are in a unrelated, and non-overlapping area, so as long as no PRD case fails, that should be fine.

**Pull request merged**
