### PR TITLE
PRD-5522 Enable excel indent

### PR DESCRIPTION
**Pull request by flatrixnet**
See related issue.

Fully working implementation for excel 2007 indent feature

### CODE REVIEW

**Comment by tmorgner** [comment]
Just one change: At the moment your test dumps the file into the root directory, where it shows up in Git has untracked file. 

Can you move the output into the "test-output" directory? For that, simply call "org.pentaho.reporting.engine.classic.core.testsupport.DebugReportRunner#createTestOutputFile()" and then change your filename to "test-output/Prd-5522.xlsx". 

The "test-output" directory is covered by a gitignore rule.

**Comment by flatrixnet** [comment]
Changed as requested

**Comment by tmorgner** [comment]
There are multiple .gitignore files. The one in the root covers all the common stuff, and the one in "engine/core" covers the test-specific excludes.

**Comment by flatrixnet** [comment]
Ok, Perfect

**Pull request merged**
