### PR TITLE
[BACKLOG-5384] Removed unused module server

### PR DESCRIPTION
**Pull request by annapopova1**
@tmorgner @lucboudreau please review

### CODE REVIEW

**Comment by tmorgner** [comment]
Luc, can you do that magic "run the checks" tool? Should not return anything suspicious. Can then be safely merged.

**Comment by lucboudreau** [comment]
On it!

**Comment by lucboudreau** [comment]
Ran it twice on Wingman. Both times it ran out of PermGen space. Will ping @brosander .

http://10.100.11.222:8080/job/wingman-ant/89/console

**Comment by annapopova1** [comment]
Unfortunately I have not access to http://10.100.11.222:8080/job/wingman-ant/89/console and can't heck it...

**Comment by lucboudreau** [comment]
This PR cannot be merged anymore. Plus Wingman doesn't like it. Sorry @tmorgner, but you'll have to process this one old-school.

**Comment by annapopova1** [comment]
Just in case updated PR.

**Comment by tmorgner** [comment]
I could not care less about Wingman's permgen problems. Poor guy should not fly if he's so terminally ill :)

As this only removes code, and as the build files are updated correctly, I deem this safe to merge.

**Pull request merged**
