### PR TITLE
[SP-1721] - Backport of PRD-5340 - Item label on Line chart is cut off a...

### PR DESCRIPTION
**Pull request by akhayrutdinov**
...t the top (5.3 Suite) (cherry picked from commit 6efa978)

@tmorgner review it please. This is a backport of https://github.com/pentaho/pentaho-reporting/pull/593

### CODE REVIEW

**Comment by akhayrutdinov** [comment]
@tmorgner, review it please. I've replaced the previous approach with the new one, cherry-picking changes from https://github.com/pentaho/pentaho-reporting/pull/593

**Comment by akhayrutdinov** [comment]
@tmorgner, @mkambol, @mdamour1976, review it please

**Comment by tmorgner** [comment]
Identical to already approved master-commit, safe to merge.

**Comment by tmorgner** [comment]
@mdamour1976 , @mkambol please merge.

**Pull request merged**
