### PR TITLE
[BISERVER-12968]-SelfLinks defined in a PRPT chart do not work on the

### PR DESCRIPTION
**Pull request by PashkovichAndrei**
server

### CODE REVIEW

**Comment by PashkovichAndrei** [comment]
@tmorgner, could you please do review?

**Comment by pamval** [comment]
@tmorgner, please review when you get the chance

**Comment by PashkovichAndrei** [comment]
@tmorgner, @pamval, @mbatchelor, could you please do review?

**Comment by PashkovichAndrei** [comment]
@tmorgner, could you please do review?

**Comment by tmorgner** [comment]
No, No, No and double no. What is it with your tendency to wrap tentacles of unrelated code to a lowest level as possible? You are pretty much coding a manual formula evaluation into that place for no particularly sane reason. STOP DOING THAT!

The formula syntax is perfectly able to express that logic as a pure formula. So if you are unhappy with the formula that is executed, wouldn't it make much more sense to change the formula, than to hack a custom interpretation into the most random location of the formula interpreter? 

I close this pull request and beg you to try to be serious in your attempts to fix the bug.

**Pull request closed without merging**
