### PR TITLE
PRD-5478 - Page header missing in the second page of the excel export

### PR DESCRIPTION
**Pull request by Aliaksandr-Kastenka**

### CODE REVIEW

**Comment by Aliaksandr-Kastenka** [comment]
@tmorgner 
Please review.

**Comment by tmorgner** [comment]
Please also test for style expressions. If a style expression is set for any of the pagebreak styles, treat the report as not valid for fast exporting.

**Comment by Aliaksandr-Kastenka** [comment]
@tmorgner 
Pull-request updated.

**Comment by pamval** [comment]
@tmorgner reporting wizard, please bless us with reviewing this pull request again

**Comment by tmorgner** [comment]
Thou shall be blessed :)
This looks good now.

**Pull request merged**
