### PR TITLE
[PRD-5916] To see the default date in the report it was necessary to …

### PR DESCRIPTION
**Pull request by stanislau-strelchanka**
[PRD-5916] To see the default date in the report it was necessary to open the parameter dialog two times (click OK)

### CODE REVIEW

**Comment by stanislau-strelchanka** [comment]
looks like a wingman issue as same tests are failing on an empty pr - #1019

@tmorgner @pamval @mchen-len-son please review

**Comment by tmorgner** [comment]
Either that or Mondrian now as a new default behaviour and therefore the golden sample of these tests no longer applies. If that is the case and the new behaviour is not a regression, then we will have to regenerate the golden samples.

**Comment by stanislau-strelchanka** [comment]
default behaviour was changed in mondrian due to MONDRIAN-1967.
created pr that updates expected results: #1020

@tmorgner @pamval @mchen-len-son please review

**Comment by stanislau-strelchanka** [comment]
@tmorgner @pamval @mchen-len-son please review

**Comment by stanislau-strelchanka** [comment]
@tmorgner @pamval @mchen-len-son please review

**Comment by stanislau-strelchanka** [comment]
@tmorgner @pamval @mchen-len-son please review

**Comment by tmorgner** [comment]
Looks good. Love the classic util-Date vs sql-Date bug fixed here.

**Pull request merged**
