### PR TITLE
[BACKLOG-5203] Change the level of logging for Report Designer

### PR DESCRIPTION
**Pull request by pedrofvteixeira**
- on startup, and with log level set to DEBUG, PRD dumps > 3k lines to the log

### CODE REVIEW

**Comment by pedrofvteixeira** [comment]
@dkincade please review

**Comment by pedrofvteixeira** [comment]
@tmorgner

**Comment by dkincade** [comment]
Refresh my memory - where is info on the priority scale? Should this be error?

Thanks,
David

On Sep 17, 2015, at 8:10 AM, Pedro Teixeira <notifications@github.com<mailto:notifications@github.com>> wrote:


@dkincade<https://github.com/dkincade> please review

-

**Comment by pedrofvteixeira** [comment]
@dkincade from lowest (priority) to highest: trace, debug, info, warn, error, fatal

**Comment by mbatchelor** [comment]
I think the setting should be WARN, not INFO

**Comment by dkincade** [comment]
agreed - please update this to Warn

**Comment by pedrofvteixeira** [comment]
@dkincade , @mbatchelor , @tmorgner updated PR accordingly, please review

**Comment by dkincade** [comment]
Thanks!

**Pull request merged**
