### PR TITLE
[PRD-6160] - When rendering html richtext containing style and fontsize specified in "px" then this text is displayed too big

### PR DESCRIPTION
**Pull request by joana-fb**
PR containing only the unit test related to PRD-6160 for QA purposes. The fix will be introduced in a following PR.
@pentaho/tatooine_dev

### CODE REVIEW

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :warning: Build finished in 13m 31s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl engine/core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.reporting.engine.classic.core.layout.HtmlRichTextProcessingTest.testScenarioPRD6160</b> (click to expand)</summary><p>

```
expected:<10.0> but was:<936.0>
```

</p></details>

  
Tests run: **823**, Failures: **1**, Skipped: **2** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/reporting/job/PR-1662/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :warning: Build finished in 10m 57s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl engine/core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.reporting.engine.classic.core.layout.HtmlRichTextProcessingTest.testScenarioPRD6160</b> (click to expand)</summary><p>

```
expected:<10.0> but was:<936.0>
```

</p></details>

  
Tests run: **823**, Failures: **1**, Skipped: **2** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/reporting/job/PR-1662/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :warning: Build finished in 9m 37s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl engine/core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.reporting.engine.classic.core.layout.HtmlRichTextProcessingTest.testScenarioPRD6160</b> (click to expand)</summary><p>

```
expected:<10.0> but was:<936.0>
```

</p></details>

  
Tests run: **823**, Failures: **1**, Skipped: **2** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/reporting/job/PR-1662/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by smmribeiro — APPROVED** [review]
Looks good!

**Comment by smmribeiro** [comment]
**Note:** the test is expected to fail until the fix itself is merged.

**Review by befc — APPROVED** [review]

**Pull request merged**
