### PR TITLE
[PRD-6054] Prevent caching the HTML attributes when they are obtained…

### PR DESCRIPTION
**Pull request by JoaoRMF**
… using expressions (they can change, and hence avoid caching them)

### CODE REVIEW

**Comment by JoaoRMF** [comment]
@pentaho/kashyyyk and @tmorgner please review

**Comment by tmorgner** [comment]
Yep, looks about right, except for that distinctive lack of test cases to validate the behaviour.

**Comment by JoaoRMF** [comment]
> Yep, looks about right, except for that distinctive lack of test cases to validate the behaviour.

I'll add them... before we merge this!

Thanks

**Comment by tmorgner** [comment]
Now it moved from good to perfect. Merged.

**Pull request merged**
