### PR TITLE
[BACKLOG-15176] After switching to maven, reporting project builds

### PR DESCRIPTION
**Pull request by e-cuellar**
complain about test errors

### CODE REVIEW

**Comment by e-cuellar** [comment]
@tmorgner

**Comment by tmorgner** [comment]
Looks good and sane. Is wingman coming to the party?

**Comment by e-cuellar** [comment]
@tmorgner Wingman seems to be misbehaving! It is failing at tests on the JNDI kind of randomly... Still researching what is going on. Thanks for your code review Thomas.

**Comment by tmorgner** [comment]
Oh, its wingman. It needs refueling. Calmly walk into the server room, take the bottle of gin from the air-vent shaft and give Wingman a good gulp of the good stuff. I'm sure as a robotic little helper he wont mind a refreshment on his chips :)

**Pull request merged**
