### PR TITLE
[PRD-5932] When using 'Row' layout in PRD, report elements set to 'vi…

### PR DESCRIPTION
**Pull request by pentaho-lmartins**
…sible=false' still display on Excel or Excel 2007 output

@duarteteixeira @pamval @mbatchelor

### CODE REVIEW

**Comment by mchen-len-son** [comment]
@tmorgner please take a look.

**Comment by tmorgner** [comment]
One thing: You cannot use "Element#isVisible" in here. That style collection contains only half the possible values and would be wrong if you use stylesheets. Use "Element#getComputedStyle#getStyleProperty" instead. This returns the computed value after the style resolver has done its magic.

**Comment by mchen-len-son** [comment]
@pentaho-lmartins can you please update changes considering the recommendations from Thomas?
thanks.

**Comment by pentaho-lmartins** [comment]
Reviewed previous pull request and added unit tests.
@mchen-len-son @tmorgner @pamval @duarteteixeira

**Comment by mchen-len-son** [comment]
@pentaho-lmartins can you please squash the commits?

**Comment by pentaho-lmartins** [comment]
Closing this PR. Will add a new one shortly.

**Pull request closed without merging**
