### PR TITLE
[SP-6574] - Backport of PIR-1523 - SQL queries for the prompts In Interactive reports are executed twice (9.3 Suite)

### PR DESCRIPTION
**Pull request by joana-fb**
original PR: https://github.com/pentaho/pentaho-reporting/pull/1677
@pentaho/tatooine_dev

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 55m 5s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl \
engine/extensions-pentaho-metadata
```
---
:ok_hand: All tests passed!
 
Tests run: **12**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/reporting-jdk11/job/PR-1682/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>



---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1h 11m 58s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl \
engine/extensions-pentaho-metadata
```
---
:ok_hand: All tests passed!
 
Tests run: **12**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/reporting-jdk11/job/PR-1682/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by befc — APPROVED** [review]

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>



---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 56m 42s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl \
engine/extensions-pentaho-metadata
```
---
:ok_hand: All tests passed!
 
Tests run: **12**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/reporting-jdk11/job/PR-1682/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
