### PR TITLE
[SP-6570] - Backport of PRD-6165 - Blank Rows Appearing on Second Sheet in Excel Export When Using Subreport (9.3 Suite)

### PR DESCRIPTION
**Pull request by joana-fb**
original PR: https://github.com/pentaho/pentaho-reporting/pull/1679
@pentaho/tatooine_dev

### CODE REVIEW

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>



---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :warning: Build finished in 1h 7m 13s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl engine/core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 2 test(s) failed:

<details><summary><b>org.pentaho.reporting.engine.classic.core.RotationTest.testHandleRotatedTextHTML on testHandleRotatedTextHTML(org.pentaho.reporting.engine.classic.core.RotationTest)</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.reporting.engine.classic.core.RotationTest.testHandleRotatedTextHTML</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **1640**, Failures: **2**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/reporting-jdk11/job/PR-1683/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by befc — APPROVED** [review]

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>



---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1h 40s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl engine/core
```
---
:ok_hand: All tests passed!
 
Tests run: **1640**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/reporting-jdk11/job/PR-1683/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
