### PR TITLE
Prd 5595 - memory leak in a flow mode

### PR DESCRIPTION
**Pull request by EgorZhuk**
Boxes were not cleaned up because check for the visibility was failing.
http://jira.pentaho.com/browse/PRD-5595

### CODE REVIEW

**Comment by tmorgner** [comment]
Ahh, basic maths. I knew it :)

Thank you for fixing this, and extra thank you for the refactoring to remove the duplicate code as well

**Comment by dkincade** [comment]
Thomas never claimed to be a genius at basic math - I am pretty sure I heard him say something to the opposite.

**Comment by tmorgner** [comment]
Right now the test is not working, as the Prd-5595 file is missing. Once there it is added Prd-5595.prpt file added I can merge it.

**Comment by EgorZhuk** [comment]
@tmorgner Sorry, my fault. Now it is present.

**Pull request merged**
