### PR TITLE
[PRD-5286] fixed the issue and refactored the saving actions

### PR DESCRIPTION
**Pull request by andrey-markelov**
@tmorgner

### CODE REVIEW

**Comment by tmorgner** [comment]
Apart from the refactoring that extracts a AbstractSaveAction class, I cannot find any actual code change. The refactored code does exactly the same as before. 

So please help me understand what is the cause of the bug and where is the fix located in this code?

**Comment by andrey-markelov** [comment]
Hi Thomas. Problem was in line 110 of SaveReportAsAction.java where code
```report.setBundle(bundle);``` replaced the "Writable" document bundle with the "Static" document bundle. I have removed this string by analogy with SaveReportAction. Also I have encapsulated generic code of saving logic in abstract class.

**Comment by tmorgner** [comment]
Wow, the silly code did that? Nice find! 

One last request: Can you please write a Unit test for this fix in the "report-designer" project? Fixes without unit-tests run the real risk of regressions a year or two down the road.

**Comment by dkincade** [comment]
I am processing this pull request now - please add the unit tests in a separate pull request...

**Pull request merged**
