### PR TITLE
PRD-5780 Chart Background not showing in Export to PDF - Insufficient data for an image

### PR DESCRIPTION
**Pull request by AliaksandrDrebenchuk**
image deflating removed

### CODE REVIEW

**Comment by pamval** [comment]
@AliaksandrDrebenchuk please review the codestyle violations.

**Comment by AliaksandrDrebenchuk** [comment]
@wingman-pentaho junit test looks like broken but the PR was successfully was built on CI. Looks like wingman doesn’t build or doesn’t publish "pentaho-reporting\engine\core" for "pentaho-reporting\engine\testcases".

http://devci.pentaho.com/job/7.1-snapshot/job/reporting-engine/189/parameters 
http://devci.pentaho.com/job/7.1-snapshot/job/reporting-engine/189/testReport/org.pentaho.reporting.engine.classic.bugs/Prd5780Test

**Comment by AliaksandrDrebenchuk** [comment]
@wingman-pentaho please take a look

**Comment by pamval** [comment]
@tmorgner can you please take a look at this pull request?

**Comment by tmorgner** [comment]
Yes, the Wingman build is broken for Ant multi-module projects and has been from the start. I explained that several times, but I guess unless we are moving to Maven to side-step that problem, we just have to live with it.

**Pull request merged**
