### PR TITLE
[BACKLOG-6746] - As a report designer, I want to use 'formulas' to set Global chart properties so these could be driven by programmatically control.

### PR DESCRIPTION
**Pull request by Aliaksandr-Kastenka**

### CODE REVIEW

**Comment by Aliaksandr-Kastenka** [comment]
@tmorgner @EgorZhuk 
Please review.

**Comment by tmorgner** [comment]
@wingman-pentaho Can you please re-order the ANT commands so that modules are built in the correct order? Building report-designer before building the engine-core or libraries is a fun exercise but not a useful one.

The build order should be "engine/core", "engine/legacy-charts", "report-designer" and finally "report-designer-charts".

**Comment by Aliaksandr-Kastenka** [comment]
@wingman-pentaho

**Comment by Aliaksandr-Kastenka** [comment]
@wingman-pentaho

**Comment by tmorgner** [comment]
As Wingman remains badly configured, checked manually. Merged.

**Comment by smaring** [comment]
call me crazy, but shouldn't things at least compile before being merged?

**Comment by EgorZhuk** [comment]
@smaring the build on wingman has wrong order.  Libraries -  engine - designer is what we need here.

**Comment by smaring** [comment]
trying to confirm by forcing the build order on devci

**Comment by smaring** [comment]
compilation confirmed ... devci picked up the changes in the wrong order ... looks OK now

**Comment by EgorZhuk** [comment]
@smaring thank you!

**Comment by tmorgner** [comment]
@smaring I had to validate manually that it does compile and that it does not break things.

For reporting, Wingman is only good for very very simple bug-fixes - it breaks as soon as a change affects more than one module. Wingman builds modules in reverse order, and that never works. I tried to warn @wingman-pentaho months ago about the build order. When you look at the order of the ant-builds, you can tell it aint gonna work.

**Pull request merged**
