### PR TITLE
[BACKLOG-7998] - Performance: Reports with TotalGroupSumFunction run …

### PR DESCRIPTION
**Pull request by prakapenka**
replace hash-map implementation with array-based structure.

### CODE REVIEW

**Comment by prakapenka** [comment]
@tmorgner please review

**Comment by tmorgner** [comment]
This looks really good. 

Given that similar code will be needed elsewhere (TotalItemCount, TotalItemMin/max use the same Hashmap<key,sequence>-structure) - can you extract the code that is dealing with the two array-lists into a separate, reusable object? This makes reusing it trivial and also allows you to properly unit-test it (which brings up the coverage numbers and makes Wingman happy).

**Comment by tmorgner** [comment]
@prakapenka Wingman still wants more coverage.

**Comment by EgorZhuk** [comment]
See #786

**Comment by tmorgner** [comment]
I think this PR can be closed.

**Pull request closed without merging**
