### PR TITLE
[PRD-5746] Border radius values are saved under an incorrect key

### PR DESCRIPTION
**Pull request by Advent51**
-fixed

### CODE REVIEW

**Comment by Advent51** [comment]
@mdamour1976 please review

**Comment by mbatchelor** [comment]
Please create a test case that covers the code in question.

**Comment by Advent51** [comment]
@mbatchelor Marc, I think there was a wingman's mistake. I can't find any test classes which were affected by my changes. May be new wingman's check remove this problem.

**Comment by tmorgner** [comment]
@Advent51 There might never have been a unit test case for that. 

You can write a new test easily by defining a report with an element that has a border-radius set. Then save the report and reload it, and check that your loaded report contains the correct property values in the expected places. 

Use org.pentaho.reporting.engine.classic.core.testsupport.ReportWritingUtil#saveAndLoad to quickly save and immediately load a MasterReport object.

**Comment by Advent51** [comment]
@tmorgner @mbatchelor test was added

**Comment by Advent51** [comment]
@wingman-pentaho I guess there are some problems with wingman

**Pull request merged**
