### PR TITLE
[BACKLOG-5203] Change the level of logging for Report Designer

### PR DESCRIPTION
**Pull request by pedrofvteixeira**
- on startup, and with log level set to DEBUG, PRD dumps > 3k lines to the log

### CODE REVIEW

**Comment by pedrofvteixeira** [comment]
@dkincade , @rmansoor , @tmorgner please review

**Comment by tmorgner** [comment]
For "org.pentaho", I would recommend to use log-level "info". This will still reduce all the "crappy" messages, but will continue to print the system information on startup. This stuff is life-saving for diagnosing machine configuration errors and assists support on problems. Having that included by default makes sure that non-technical users provide good logs when asking for help.

For "org.pentaho.reporting.libraries.base.util.LoggingStopWatch": Dont change that. These messages do not go into the main log. They are used to fill the performance metrics log. Setting it to warn will disable that collection.

**Comment by pedrofvteixeira** [comment]
@tmorgner changed accordingly, please review

**Comment by mbatchelor** [comment]
I think the setting should be WARN, not INFO

**Comment by pedrofvteixeira** [comment]
@dkincade , @mbatchelor , @tmorgner updated PR accordingly, please review

**Comment by dkincade** [comment]
Please make same request for 6.0.0.0 branch

**Comment by pedrofvteixeira** [comment]
@dkincade leaving 6.0.0.0 PR linked here: https://github.com/pentaho/pentaho-reporting/pull/674

**Comment by dkincade** [comment]
If the user has an issue that needs diagnosing, we can ask them to change the log level ...

**Pull request merged**
