### PR TITLE
PRD-5816 Cannot filter by null values in PRD and Report Viewer

### PR DESCRIPTION
**Pull request by AliaksandrDrebenchuk**
changing "= null" to "is NULL" was added

### CODE REVIEW

**Comment by kolinus** [comment]
@tmorgner, @EgorZhuk   could you please take a look

**Comment by EgorZhuk** [comment]
@tmorgner @kolinus  didn't work for me at least with inmemory sampledata report and custom postgres. Probably works with mysql

**Comment by tmorgner** [comment]
No way I let this pass. We do not rewrite queries in the SQL datasource. We simply cannot guarantee that we do not break existing reports. JDBC drivers are widely varying in their support for features and the general contract around this is: The user is responsible for generating correct SQL.

JDBC-lite drivers like Hive or certain crude proprietary JDBC interfaces may not support the IS NULL and may error out now. Remember: Just because some databases support a feature does not mean all do. 

For null tests, a raw SQL user has to use the coalesce function, as explained in this forum thread.

http://forums.pentaho.com/showthread.php?74001-PRD-3-5-creation-of-SQL-query-for-conditional-null-or-non-null-value

To fix PIR (as in the case referenced in PRD-5816) implement this fix in the SQLGenerator of the metadata layer. At least there you have information about the SQL dialect used and can make a sane decision on whether your construct will be supported. And most importantly: You are not breaking other peoples reports.

Introducing a potentially breaking change like that will only pass my filters if it is guarded by a feature switch and if the original behaviour is the default.

**Comment by tmorgner** [comment]
In addition: Your change unconditionally breaks queries that use parameter values in a function:

       WHERE aColumn = CONCAT("Prefix", ${param}, "suffix") 

would be rewritten to:

       WHERE aColumn = CONCAT("Prefix", ${param} IS NULL, "suffix") 


If you want to safely rewrite SQL, you have to be aware of the context where a variable is used. That requires a proper SQL parser and a lot more code than just a string replacement. You'd also would need to be aware of the underlying database (SQL has so many extensions that the term "standard" does no longer apply to it).

**Pull request closed without merging**
