### PR TITLE
[PRD-5762] - PDI as a datasource in PRD. Fields not being read from t…

### PR DESCRIPTION
**Pull request by stanislau-strelchanka**
[PRD-5762] - PDI as a datasource in PRD. Fields not being read from transformation.

### CODE REVIEW

**Comment by stanislau-strelchanka** [comment]
@wingman-pentaho can you please assist with errors

**Comment by tmorgner** [comment]
@wingman-pentaho Isn't dev-lib supposed to be an optional directory? And the error points to line 2084 of subfloor, which is in master is a "taskdef" for the JUnit ant-task. It doesn't even mention "devlib" anywhere near there. Makes me wonder what subfloor.xml wingman is actually using.

**Comment by stanislau-strelchanka** [comment]
@mkambol, @mdamour1976, @tmorgner, @mchen-len-son, @pamval  please review

**Comment by stanislau-strelchanka** [comment]
@mkambol, @mdamour1976, @tmorgner, @mchen-len-son, @pamval, @wingman-pentaho 
'compile' target is used from 'build.assembly.sequential.xml' and it didn't depend on 'init' which
is responsible for creating devlib and other folders

please review

**Comment by stanislau-strelchanka** [comment]
moved wingman fix to #840

**Pull request merged**
